name: example
description: Example of Adaptive Cards.
author: Neohelden GmbH <hello@neohelden.com>
homepage: https://neohelden.com
version: 0.2.0-nullsafety.0

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  url_launcher: ^6.0.2
  http: ^0.13.1

  adaptive_theme: ^2.2.0

  flutter_adaptive_cards:
    path: ..

dev_dependencies:

  # Enforces effective dart code style
  effective_dart: ^1.3.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
    - lib/host_config_dark.json
    - lib/host_config_light.json
    - lib/text_block/
    - lib/image/
    - lib/container/
    - lib/column_set/
    - lib/column/
    - lib/fact_set/
    - lib/image_set/
    - lib/action_set/
    - lib/action_open_url/
    - lib/action_submit/
    - lib/action_show_card/
    - lib/inputs/input_text/
    - lib/inputs/input_number/
    - lib/inputs/input_date/
    - lib/inputs/input_time/
    - lib/inputs/input_toggle/
    - lib/inputs/input_choice_set/
    - lib/media/
    - lib/samples/

publish_to: none