name: flutter_adaptive_cards
description: Adaptive Cards are platform-agnostic snippets of UI, authored in JSON, that apps and services can openly exchange.
version: 0.2.0-nullsafety.0
homepage: https://github.com/neohelden/Flutter-AdaptiveCards

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # General
  http: ^0.13.1
  provider: ^5.0.0
  uuid: ^3.0.4
  ## Localization
  intl: ^0.17.0

  # Content
  ## Video player with controls
  chewie: ^1.0.0
  video_player: ^2.1.1
  ## Markdown renderer
  flutter_markdown: ^0.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.14.3
  mockito: ^5.0.5

flutter:
